apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: http          # must match your frontend Service port name
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
