apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Blessedmine/microservice_CICD-'
    targetRevision: main
    path: Product
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
