apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Blessedmine/microservice_CICD-'
    targetRevision: main
    path: shopping-cart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
