apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 495599739945.dkr.ecr.us-east-1.amazonaws.com/product:v1
          ports:
            - containerPort: 3001