apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: <registry>/auth-service:latest
          ports:
            - containerPort: 3001