# shopping-cart-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: 495599739945.dkr.ecr.us-east-1.amazonaws.com/shopping-cart:v1
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: default
spec:
  selector:
    app: shopping-cart
  ports:
    - port: 80
      targetPort: 3002
  type: ClusterIP
