apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
  namespace: shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: <registry>/auth-service:latest
          ports:
            - containerPort: 3002